feat(dotfiles-dev): add test command to run tests in containerized environment

diff --git a/bin/dotfiles-dev b/bin/dotfiles-dev
--- a/bin/dotfiles-dev
+++ b/bin/dotfiles-dev
@@ -10,9 +10,46 @@ if [[ $# -lt 1 ]]; then
     exit 0
 fi
 
-run_cmd_shell() {
-    local base="ubuntu"
-    local tag="latest"
+launch_container() {
+    local img="$1"
+    local tag="$2"
+    shift 2
+
+    if ! [ -r ./tests/platforms/${img}.dockerfile ]; then
+        printf '%s\n' "dotfiles-dev: unsupported container image '$img'" >&2
+        exit 1
+    fi
+
+    local uid=$(id -u)
+    local gid=$(id -g)
+    local u_name=$(id -n -u)
+    local g_name=$(id -n -g)
+
+    podman build \
+        --build-arg=DOCKER_USER_UID=${uid}      \
+        --build-arg=DOCKER_USER_GID=${gid}      \
+        --build-arg=DOCKER_USER_NAME=${u_name}  \
+        --build-arg=DOCKER_USER_GROUP=${g_name} \
+        --build-arg=BASE_IMAGE_VERSION=${tag}   \
+        -t dotfiles-dev-${img}-${tag}          \
+        -f ./tests/platforms/${img}.dockerfile \
+        ${PWD}
+
+    if [ $? -ne 0 ] ; then
+        exit 1
+    fi
+
+    podman run \
+        --rm \
+        --user ${uid}:${gid} \
+        --userns=keep-id:uid=${uid},gid=${gid} \
+        -v "${PWD}:/home/${u_name}/dotfiles:z" \
+        -it dotfiles-dev-${img}-${tag} \
+        "$@"
+}
+
+run_cmd_test() {
+    local platform="fedora:latest"
 
     while [[ $# -gt 0 ]];
     do
@@ -24,22 +61,10 @@ run_cmd_shell() {
                 fi
 
                 shift
-                base=$1
+                platform=$1
                 ;;
             --platform=*)
-                base=${1#--platform=}
-                ;;
-            -t|--tag)
-                if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
-                    printf '%s\n' "dotfiles-dev: missing mandatory value for option '$1'" >&2
-                    exit 1
-                fi
-
-                shift
-                tag=$1
-                ;;
-            --tag=*)
-                tag=${1#--tag=}
+                platform=${1#--platform=}
                 ;;
             -*)
                 printf '%s\n' "dotfiles-dev: unknown option '$1'" >&2
@@ -54,39 +79,63 @@ run_cmd_shell() {
         shift
     done
 
-    local uid=$(id -u)
-    local gid=$(id -g)
-    local u_name=$(id -n -u)
-    local g_name=$(id -n -g)
-
-    podman build \
-        --build-arg=DOCKER_USER_UID=${uid}      \
-        --build-arg=DOCKER_USER_GID=${gid}      \
-        --build-arg=DOCKER_USER_NAME=${u_name}  \
-        --build-arg=DOCKER_USER_GROUP=${g_name} \
-        --build-arg=BASE_IMAGE_VERSION=${tag}   \
-        -t dotfiles-dev-${base}-${tag}          \
-        -f ./tests/platforms/${base}.dockerfile \
-        ${PWD}
-
-    if [ $? -ne 0 ] ; then
-        exit 1
+    IFS=':' read -r base tag <<< "${platform}"
+    if [ -z "${tag-}" ]; then
+        local tag=latest
     fi
 
-    podman run \
-        --rm \
-        --user ${uid}:${gid} \
-        --userns=keep-id:uid=${uid},gid=${gid} \
-        -v "${PWD}:/home/${u_name}/dotfiles:z" \
-        -it dotfiles-dev-${base}-${tag}
+    launch_container "${base}" "${tag}" ./bin/dotfiles doctor
+    exit
+}
 
-    exit 0
+run_cmd_shell() {
+    local platform="fedora:latest"
+
+    while [[ $# -gt 0 ]];
+    do
+        case $1 in
+            -p|--platform)
+                if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
+                    printf '%s\n' "dotfiles-dev: missing mandatory value for option '$1'" >&2
+                    exit 1
+                fi
+
+                shift
+                platform=$1
+                ;;
+            --platform=*)
+                platform=${1#--platform=}
+                ;;
+            -*)
+                printf '%s\n' "dotfiles-dev: unknown option '$1'" >&2
+                exit 1
+                ;;
+            *)
+                printf '%s\n' "dotfiles-dev: unknown argument '$1'" >&2
+                exit 1
+                ;;
+        esac
+
+        shift
+    done
+
+    IFS=':' read -r base tag <<< "${platform}"
+    if [ -z "${tag-}" ]; then
+        local tag=latest
+    fi
+
+    launch_container "${base}" "${tag}" bash
+    exit
 }
 
 case $1 in
     shell)
         shift
         run_cmd_shell "$@"
+        ;;
+    test)
+        shift
+        run_cmd_test "$@"
         ;;
     *)
         printf '%s\n' 'dotfiles-dev: unknown command ${1}' >&2
